language: python
sudo: true

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"

before_install:
  - sudo apt-get install luarocks
  - luarocks install luasocket
  - luarocks install luabitop

install:
  - luarocks make

script:
  - lua dataminer.lua
